# Generated by Django 2.2.1 on 2019-05-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('teacher_id', models.CharField(max_length=20)),
                ('lessons', models.CharField(max_length=15)),
                ('classroom', models.CharField(max_length=4)),
                ('attendance_date', models.DateField()),
                ('timing', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
