# Generated by Django 2.2.1 on 2019-05-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190522_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
