# Generated by Django 2.2.1 on 2019-05-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190524_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
