# Generated by Django 2.2.1 on 2019-06-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190601_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=7)),
                ('lesson', models.CharField(max_length=20)),
                ('teacher_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=7)),
                ('dayname', models.CharField(max_length=20)),
                ('lesson_1', models.CharField(max_length=20)),
                ('lesson_2', models.CharField(max_length=20)),
                ('lesson_3', models.CharField(max_length=20)),
            ],
        ),
    ]
