# Generated by Django 2.2.1 on 2019-06-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_teacherlesson_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='studentaffairs',
            name='age',
        ),
        migrations.RemoveField(
            model_name='studentaffairs',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='studentaffairs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studentaffairs',
            name='is_studentaffairs',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_teacher',
        ),
    ]
