# Generated by Django 2.2.1 on 2019-06-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190609_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
