# Generated by Django 2.2.1 on 2019-06-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190609_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classroom',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lessons',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
