# Generated by Django 2.2.1 on 2019-06-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20190613_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
