# Generated by Django 2.2.1 on 2019-06-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_delete_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=7)),
                ('dayname', models.CharField(max_length=20)),
                ('lesson', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=202)),
            ],
        ),
    ]
