# Generated by Django 2.2.1 on 2019-06-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_timetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='time',
            new_name='l_time',
        ),
    ]
